# Generated by Django 3.0.2 on 2020-02-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Enrollment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
