# Generated by Django 3.0.2 on 2020-02-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_students_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='Enrollment',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='students',
            name='Gmail',
            field=models.CharField(max_length=30),
        ),
    ]
