# Generated by Django 3.0.2 on 2020-02-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20200210_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('DOB', models.CharField(max_length=10)),
            ],
        ),
    ]
