# Generated by Django 3.0.2 on 2020-02-20 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_students_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='clg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='song.college'),
        ),
    ]
