# Generated by Django 3.0.2 on 2020-02-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_students_clg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
