# Generated by Django 3.0.2 on 2020-02-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_auto_20200220_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
