# Generated by Django 3.0.2 on 2020-03-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_auto_20200225_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='univercity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
